### ISSUE TITLE
Insert point take 10 second , does it normal.

### ISSUE THREAD

**Issue by xiaopenghuang** [ethz-asl/volumetric_mapping#64]
I have a pointcloud2 topic ,which like 
```
header: 
  seq: 81
  stamp: 
    secs: 1496933331
    nsecs: 173401025
  frame_id: stereo
height: 1
width: 71719
fields: 
  - 
    name: x
    offset: 0
    datatype: 7
    count: 1
  - 
    name: y
    offset: 4
    datatype: 7
    count: 1
  - 
    name: z
    offset: 8
    datatype: 7
    count: 1
is_bigendian: False
point_step: 16
row_step: 1147504
data: [234, 159, 144, 191, 123, 61, 31, 191, 238
```
every time i call `volumetric_mapping::OctomapManager::insertPointcloudWithTf` , it take 10-15 second to finish the function, is it normal.

the configuration is :

```
	<param name="tf_frame" value="world"/>
	<param name="resolution" value="0.15" />
	<param name="visualize_min_z" value="0" />
	<param name="visualize_max_z" value="4.0" />
	<!-- <param name="filter_speckles" value="true" />  -->
<!-- 	<param name="treat_unknown_as_occupied" value="true" /> 
 -->	
 	<param name="sensor_max_range" value="4.0" /> 
	<param name="full_image_width" value="600" /> 
	<param name="full_image_height" value="300" /> 
	<param name="map_publish_frequency" value="5" /> 
```

if i use` octomap_server` pkg , which i can get almost realtime output.

Anyone can help me. Is insertpointcloud any different from the octomap_server.
