### ISSUE TITLE
 getting a transform error

### ISSUE THREAD

**Issue by rnunziata** [ethz-asl/volumetric_mapping#71]
I am getting a transform error
`:Requested transform time older than cache limit`  

If I change the tf_frame parameter to the optical frame rather then the world frame then I do not get the error.

can you help me understand it.

**Comment by helenol** [comment]
Can you confirm that the transformation between these two trees exists, either in rviz or using tf tools? http://wiki.ros.org/tf/Debugging%20tools

**Comment by ZacharyTaylor** [comment]
Also if you are playing from a bag are you remembering to use "--clock"

**Comment by rnunziata** [comment]
Here is the data: Thank you for looking at this.

```
>>  **************************  rosrun tf world openni_rgb_optical_frame

Frames:
Frame: openni_rgb_optical_frame published by unknown_publisher Average Delay: 0.43345 Max Delay: 0.466913

All Broadcasters:
Node: unknown_publisher 2.05562 Hz, Average Delay: 0.43345 Max Delay: 0.466913



RESULTS: for world to openni_rgb_optical_frame
Chain is: world -> openni_rgb_optical_frame
Net delay     avg = 0.711545: max = 0.965144



>> ******************************   roswtf

Loaded plugin tf.tfwtf
Package: ORB_SLAM2
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules
running tf checks, this will take a second...
... tf checks complete

Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following node subscriptions are unconnected:
 * /octomap_manager:
   * /cam0/camera_info
   * /cam1/camera_info
   * /input_octomap
   * /tf_static
   * /disparity
 * /rviz:
   * /tf_static

```

![rosgraph](https://user-images.githubusercontent.com/5377074/33566726-e0ccbf64-d8ee-11e7-88a8-381144da8b6b.jpg)
![frames](https://user-images.githubusercontent.com/5377074/33566731-e4bb5e64-d8ee-11e7-96f9-bcadf529dedd.jpg)


>> **************************************** launch file
```

<launch>
  <arg name="rviz_cfg"            default="$(find ORB_SLAM2)/launch/config/octomap_manager.rviz" />
  <arg name="depthsystem1"        default="depth2mono.py"/> <!-- depth2sfm.py depth2mono.py -->

  <!-- creates a depth message and publishes image depth and camera info under new topic  conversion-->
  <node pkg="depth2orb" type="$(arg depthsystem1)" name="depth2orb" output="screen">      
    <param name="camera_frame"  value="openni_rgb_optical_frame"/>                       
  </node>

  <!-- estimates camera pose creates a tracking transform for the pose -->
  <node pkg="ORB_SLAM2" type="RGBD" name="rgbd_odometry" 
        args="/home/rjn/catkin_rosmake_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt /home/rjn/catkin_rosmake_ws/src/ORB_SLAM2/Examples/RGB-D/TUM1.yaml">   
    <remap from="/camera/rgb/image_raw" to="/conversion/rgb/image"/>  
    <remap from="/camera/depth_registered/image_raw" to="/conversion/depth/image"/>  
    <param name="base_frame"  type="string" value="world" />  
    <param name="camera_frame" type="string" value="openni_rgb_optical_frame" />  
  </node>
    
  <node pkg="nodelet" type="nodelet" name="standalone_nodelet"  args="manager" output="screen"/>
 
  <!-- creates point cloud form depth and image messages -->
  <node pkg="nodelet" type="nodelet" name="points_xyzrgb" args="load depth_image_proc/point_cloud_xyzrgb standalone_nodelet">
    <remap from="rgb/camera_info"             to="/conversion/rgb/camera_info" />  
    <remap from="rgb/image_rect_color"        to="/conversion/rgb/image"/>  
    <remap from="depth_registered/image_rect" to="/conversion/depth/image"/>  
    <remap from="depth_registered/points"     to="/cloud"/>
    <param name="queue_size"    type="int"    value="50"/>     
  </node>
 
  <node  pkg="octomap_world" type="octomap_manager" name="octomap_manager" output="screen">         
    <param name="tf_frame"  type="string" value="world"/>  
    <remap from="pointcloud"     to="/cloud"/>      
    <param name="map_publish_frequency"  type="double" value="5.0"/>     
    <param name="resolution"  type="double" value="0.5"/>   
    <param name="sensor_max_range" type="double" value="1000.0"/>  
    <param name="octomap_file" type="string" value="/home/rjn/.ros/octomap.bt"/>           
  </node> 

  
  <node pkg="rviz" type="rviz" name="rviz" args="-d $(arg rviz_cfg)"/>

</launch>

```

**Comment by helenol** [comment]
Thanks a lot for the detailed results! This is very helpful.
I checked, default TF cache should be 10 seconds and your average delay is waaaay lower than that... So the pointcloud is for sure published in the `openni_rgb_optical_frame` frame (that's what's in the header frame_id)?

Looks like the issue is here:
https://github.com/ethz-asl/volumetric_mapping/blob/master/octomap_world/src/octomap_manager.cc#L457

Could you perhaps output what value `timestamp_age` takes here, in addition to `ros::Time::now()` and `time_to_lookup`?

Seems like some kind of clock mismatch, though that would show up in the tf stuff as well.

Actually can you also confirm that the pointcloud published has a timestamp that isn't 0? Perhaps this is the issue.

**Comment by rnunziata** [comment]
Here are transforms from rostopic echo /tf ....I will get back to you on the other data  

```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1512410340
        nsecs: 387207031
      frame_id: world
    child_frame_id: openni_rgb_optical_frame
    transform: 
      translation: 
        x: -0.221373125911
        y: -1.13990700245
        z: 4.0663151741
      rotation: 
        x: 0.0107588595197
        y: -0.0435342013606
        z: -0.0606918633618
        w: 0.997148695657
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1512410340
        nsecs: 859630107
      frame_id: world
    child_frame_id: openni_rgb_optical_frame
    transform: 
      translation: 
        x: -0.227462023497
        y: -1.13106560707
        z: 4.07146978378
      rotation: 
        x: 0.0126627749149
        y: -0.0423238945162
        z: -0.0606810133379
        w: 0.997179098294
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1512410341
        nsecs: 338864088
      frame_id: world
    child_frame_id: openni_rgb_optical_frame
    transform: 
      translation: 
        x: -0.221434906125
        y: -1.1463881731
        z: 4.0929775238
      rotation: 
        x: 0.0110110701047
        y: -0.0453929583649
        z: -0.0620696405364
        w: 0.996978232441

```
