### ISSUE TITLE
Not generating map

### ISSUE THREAD

**Issue by rnunziata** [ethz-asl/volumetric_mapping#72]
I have a miss understanding on how volumetric mapping works.  I am displaying a narrow z range in the free map space. I thought the octomap map would track with the camera position but it does not. It does not plot a map out even if I save_map all I get is the range specified which is always the z range of the last image processed in a fixed location. How can I plot a map...I must be doing something incorrect. My parameters are below.  If I used a video file that is not driving down a road by just circles a desk or office area it works fine and builds a good map.

![rviz_screenshot_m2017_12_06-16_38_03](https://user-images.githubusercontent.com/5377074/33686948-7dc0a13a-daa4-11e7-97f1-5c623421559f.png)

```
  <node  pkg="octomap_world" type="octomap_manager" name="octomap_manager" output="screen">         
    <param name="tf_frame"     type="string" value="world"/> 
    <param name="robot_frame"  type="string" value="openni_rgb_optical_frame"/>   
    <param name="full_image_width"  type="double" value="640"/>    
    <param name="full_image_height"  type="double" value="480"/>         
    <remap from="pointcloud"     to="/cloud"/>      
    <param name="map_publish_frequency"  type="double" value="2.0"/>     
    <param name="resolution"  type="double" value="0.2"/>   
    <param name="sensor_max_range" type="double" value="1000.0"/>  <!-- larger more forground 150 -->
    <param name="visualize_max_z"  type="double" value="90.0"/>  
    <param name="visualize_min_z"  type="double" value="80.0"/>    <!-- larger less backgroud  50-->
    <param name="min_height_free_space"  type="double" value="3.0"/> 
    <param name="change_detection_enabled"  type="bool" value="False"/> 
    <!-- param name="octomap_file" type="string" value="/home/rjn/.ros/king_street.bt"/ -->           
  </node> 
```
```
rostopic echo /octomap_manager/octomap_free | pg
markers: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: openni_rgb_optical_frame
    ns: map
    id: 0
    type: 6
    action: 2

rostopic echo /cloud | pg
header: 
  seq: 37
  stamp: 
    secs: 1512597190
    nsecs: 989447116
  frame_id: openni_rgb_optical_frame
height: 256
width: 512
fields: 
  - 
    name: x
    offset: 0
    datatype: 7
    count: 1

```
